version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:80

  MariaDB_db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 4000:80
    environment:
      - PMA_ARBITRARY=1
