version: '3.9'

services:
  php-env:
    image: php:8.0-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 4000:4000
    environment:
      - PMA_ARBITRARY=1
