version: '3.9'

services:
 php-env:
   build: .
   volumes:
     - ./src:/var/www/html
   ports:
     - 3000:80
  
 mysql_server:
   image: mysql:latest
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root

 phpmyadmin:
   image: phpmyadmin:latest
   restart: always
   ports:
     - 4000:80
   environment:
     - PMA_ARBITRARY=1